# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/odroid/Downloads/PowerOptimizer.android

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/odroid/Downloads/PowerOptimizer.android

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/odroid/Downloads/PowerOptimizer.android/CMakeFiles /home/odroid/Downloads/PowerOptimizer.android/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/odroid/Downloads/PowerOptimizer.android/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named powercontrol

# Build rule for target.
powercontrol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 powercontrol
.PHONY : powercontrol

# fast build rule for target.
powercontrol/fast:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/build
.PHONY : powercontrol/fast

DPMCompensate.o: DPMCompensate.c.o
.PHONY : DPMCompensate.o

# target to build an object file
DPMCompensate.c.o:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/DPMCompensate.c.o
.PHONY : DPMCompensate.c.o

DPMCompensate.i: DPMCompensate.c.i
.PHONY : DPMCompensate.i

# target to preprocess a source file
DPMCompensate.c.i:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/DPMCompensate.c.i
.PHONY : DPMCompensate.c.i

DPMCompensate.s: DPMCompensate.c.s
.PHONY : DPMCompensate.s

# target to generate assembly for a file
DPMCompensate.c.s:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/DPMCompensate.c.s
.PHONY : DPMCompensate.c.s

PowerFuzzy.o: PowerFuzzy.c.o
.PHONY : PowerFuzzy.o

# target to build an object file
PowerFuzzy.c.o:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/PowerFuzzy.c.o
.PHONY : PowerFuzzy.c.o

PowerFuzzy.i: PowerFuzzy.c.i
.PHONY : PowerFuzzy.i

# target to preprocess a source file
PowerFuzzy.c.i:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/PowerFuzzy.c.i
.PHONY : PowerFuzzy.c.i

PowerFuzzy.s: PowerFuzzy.c.s
.PHONY : PowerFuzzy.s

# target to generate assembly for a file
PowerFuzzy.c.s:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/PowerFuzzy.c.s
.PHONY : PowerFuzzy.c.s

actuator.o: actuator.c.o
.PHONY : actuator.o

# target to build an object file
actuator.c.o:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/actuator.c.o
.PHONY : actuator.c.o

actuator.i: actuator.c.i
.PHONY : actuator.i

# target to preprocess a source file
actuator.c.i:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/actuator.c.i
.PHONY : actuator.c.i

actuator.s: actuator.c.s
.PHONY : actuator.s

# target to generate assembly for a file
actuator.c.s:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/actuator.c.s
.PHONY : actuator.c.s

cfsqp.o: cfsqp.c.o
.PHONY : cfsqp.o

# target to build an object file
cfsqp.c.o:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/cfsqp.c.o
.PHONY : cfsqp.c.o

cfsqp.i: cfsqp.c.i
.PHONY : cfsqp.i

# target to preprocess a source file
cfsqp.c.i:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/cfsqp.c.i
.PHONY : cfsqp.c.i

cfsqp.s: cfsqp.c.s
.PHONY : cfsqp.s

# target to generate assembly for a file
cfsqp.c.s:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/cfsqp.c.s
.PHONY : cfsqp.c.s

kalman.o: kalman.c.o
.PHONY : kalman.o

# target to build an object file
kalman.c.o:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/kalman.c.o
.PHONY : kalman.c.o

kalman.i: kalman.c.i
.PHONY : kalman.i

# target to preprocess a source file
kalman.c.i:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/kalman.c.i
.PHONY : kalman.c.i

kalman.s: kalman.c.s
.PHONY : kalman.s

# target to generate assembly for a file
kalman.c.s:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/kalman.c.s
.PHONY : kalman.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/main.c.s
.PHONY : main.c.s

mpiserver.o: mpiserver.c.o
.PHONY : mpiserver.o

# target to build an object file
mpiserver.c.o:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/mpiserver.c.o
.PHONY : mpiserver.c.o

mpiserver.i: mpiserver.c.i
.PHONY : mpiserver.i

# target to preprocess a source file
mpiserver.c.i:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/mpiserver.c.i
.PHONY : mpiserver.c.i

mpiserver.s: mpiserver.c.s
.PHONY : mpiserver.s

# target to generate assembly for a file
mpiserver.c.s:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/mpiserver.c.s
.PHONY : mpiserver.c.s

poweropt.o: poweropt.c.o
.PHONY : poweropt.o

# target to build an object file
poweropt.c.o:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/poweropt.c.o
.PHONY : poweropt.c.o

poweropt.i: poweropt.c.i
.PHONY : poweropt.i

# target to preprocess a source file
poweropt.c.i:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/poweropt.c.i
.PHONY : poweropt.c.i

poweropt.s: poweropt.c.s
.PHONY : poweropt.s

# target to generate assembly for a file
poweropt.c.s:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/poweropt.c.s
.PHONY : poweropt.c.s

qld.o: qld.c.o
.PHONY : qld.o

# target to build an object file
qld.c.o:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/qld.c.o
.PHONY : qld.c.o

qld.i: qld.c.i
.PHONY : qld.i

# target to preprocess a source file
qld.c.i:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/qld.c.i
.PHONY : qld.c.i

qld.s: qld.c.s
.PHONY : qld.s

# target to generate assembly for a file
qld.c.s:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/qld.c.s
.PHONY : qld.c.s

util.o: util.c.o
.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i
.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s
.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/util.c.s
.PHONY : util.c.s

verror.o: verror.c.o
.PHONY : verror.o

# target to build an object file
verror.c.o:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/verror.c.o
.PHONY : verror.c.o

verror.i: verror.c.i
.PHONY : verror.i

# target to preprocess a source file
verror.c.i:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/verror.c.i
.PHONY : verror.c.i

verror.s: verror.c.s
.PHONY : verror.s

# target to generate assembly for a file
verror.c.s:
	$(MAKE) -f CMakeFiles/powercontrol.dir/build.make CMakeFiles/powercontrol.dir/verror.c.s
.PHONY : verror.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... powercontrol"
	@echo "... rebuild_cache"
	@echo "... DPMCompensate.o"
	@echo "... DPMCompensate.i"
	@echo "... DPMCompensate.s"
	@echo "... PowerFuzzy.o"
	@echo "... PowerFuzzy.i"
	@echo "... PowerFuzzy.s"
	@echo "... actuator.o"
	@echo "... actuator.i"
	@echo "... actuator.s"
	@echo "... cfsqp.o"
	@echo "... cfsqp.i"
	@echo "... cfsqp.s"
	@echo "... kalman.o"
	@echo "... kalman.i"
	@echo "... kalman.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mpiserver.o"
	@echo "... mpiserver.i"
	@echo "... mpiserver.s"
	@echo "... poweropt.o"
	@echo "... poweropt.i"
	@echo "... poweropt.s"
	@echo "... qld.o"
	@echo "... qld.i"
	@echo "... qld.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
	@echo "... verror.o"
	@echo "... verror.i"
	@echo "... verror.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

