/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
/*                                                      */
/* File:  PowerFuzzy.h                                  */
/*                                                      */
/* Author: Automatically generated by Xfuzzy            */
/*                                                      */
/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

#ifndef XFUZZY
#define XFUZZY
/*------------------------------------------------------*/
/* Fuzzy Number                                         */
/*------------------------------------------------------*/

 typedef struct {
   double (* equal)(double x);
   double (* center)();
   double (* basis)();
   double (* param)(int i);
 } Consequent;

 typedef struct {
   double min;
   double max;
   double step;
   double (* imp)(double a, double b);
   double (* also)(double a, double b);
   int length;
   double* degree;
   int inputlength;
   double* input;
   Consequent* conc;
 } FuzzyNumber2;

#endif /* XFUZZY */


#ifndef XFUZZY_PowerFuzzy
#define XFUZZY_PowerFuzzy
/*------------------------------------------------------*/
/* Inference Engine                                     */
/*------------------------------------------------------*/

void PowerFuzzyInferenceEngine(double Error, double ErrorSum, double* Out);

#endif /* XFUZZY_PowerFuzzy */
