/*********************************************************************************
 This file is part of Bricktop Power Manager.

    Bricktop Power Manager is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Bricktop Power Manager is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Bricktop Power Manager.  If not, see <http://www.gnu.org/licenses/>. 
***********************************************************************************/

/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
/*                                                      */
/* File:  PowerFuzzy.h                                  */
/*                                                      */
/* Author: Automatically generated by Xfuzzy            */
/*                                                      */
/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

#ifndef XFUZZY
#define XFUZZY
/*------------------------------------------------------*/
/* Fuzzy Number                                         */
/*------------------------------------------------------*/

 typedef struct {
   double (* equal)(double x);
   double (* center)();
   double (* basis)();
   double (* param)(int i);
 } Consequent;

 typedef struct {
   double min;
   double max;
   double step;
   double (* imp)(double a, double b);
   double (* also)(double a, double b);
   int length;
   double* degree;
   int inputlength;
   double* input;
   Consequent* conc;
 } FuzzyNumber2;

#endif /* XFUZZY */


#ifndef XFUZZY_PowerFuzzy
#define XFUZZY_PowerFuzzy
/*------------------------------------------------------*/
/* Inference Engine                                     */
/*------------------------------------------------------*/

void PowerFuzzyInferenceEngine(double Error, double ErrorSum, double* Out);

#endif /* XFUZZY_PowerFuzzy */
